### ISSUE TITLE
Widget seems to be right aligned?

### ISSUE THREAD

**Issue by ramonsaraiva** [jmrivas86/django-json-widget#12]
Seems like the widget floats to the right, leaving this white spacement in-between the column name and the value:

![image](https://user-images.githubusercontent.com/5559120/46027328-f7011880-c0c3-11e8-902f-8c046643bf3f.png)

I think this happens because of https://github.com/jmrivas86/django-json-widget/blob/master/django_json_widget/templates/django_json_widget.html#L1

Any special reason to have that `float: right`? Can that be removed?

**Comment by ramonsaraiva** [comment]
Prolly related to the `90%` width, actually.. cause `10%` in this screen is actually quite a bit, so it happens to align a bit to the right

**Comment by vinaypai** [comment]
@ramonsaraiva you're right. It's because of the float:right combined with the 90% width which can be too much on wide screens. I have it fixed (among other things) in my [fork]https://github.com/vinaypai/django-json-widget/tree/customconfig). I will issue a pull request once I have a chance to update the documentation with the new features and verify it works with older versions of django and python.

**Comment by jmrivas86** [comment]
I close this issue because it was solved in #20
